// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqZTJR50LYDI8bC90oTcKRCeLc1FRaIE',
    appId: '1:116678508119:web:c5af07e6cd5cd08f422d12',
    messagingSenderId: '116678508119',
    projectId: 'rotiku-vsga',
    authDomain: 'rotiku-vsga.firebaseapp.com',
    storageBucket: 'rotiku-vsga.firebasestorage.app',
    measurementId: 'G-SW59DQFXQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBo-yYmS4gg20oNX5OaHlflm8VPzkN6H4',
    appId: '1:116678508119:android:174318f5203e989c422d12',
    messagingSenderId: '116678508119',
    projectId: 'rotiku-vsga',
    storageBucket: 'rotiku-vsga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPBHwRDv9jOgp_uh5sxvvawLWzyI-VOc',
    appId: '1:116678508119:ios:5aaa6d4fcedde690422d12',
    messagingSenderId: '116678508119',
    projectId: 'rotiku-vsga',
    storageBucket: 'rotiku-vsga.firebasestorage.app',
    iosBundleId: 'com.example.rotiku',
  );
}
